/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shuihucard_MainActivity */

#ifndef _Included_com_shuihucard_MainActivity
#define _Included_com_shuihucard_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shuihucard_MainActivity
 * Method:    TestLog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_shuihucard_MainActivity_TestLog
  (JNIEnv *, jobject);

/*
 * Class:     com_shuihucard_MainActivity
 * Method:    JniGetByteArr
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_shuihucard_MainActivity_JniGetByteArr
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_shuihucard_MainActivity
 * Method:    getOffset
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_shuihucard_MainActivity_getOffset
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_shuihucard_MainActivity
 * Method:    getBmpSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_shuihucard_MainActivity_getBmpSize
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_shuihucard_MainActivity
 * Method:    DecodeBmp
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_shuihucard_MainActivity_DecodeBmp
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
